var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,d=[];!(b=a.next()).done;)d.push(b.value);return d};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
function skillset_to_NodeLink(a){var b=[],d=[],c;for(c in a){current_project=a[c];b.push({group:"1",id:c});for(var f in current_project["Programming/Scripting Languages"]){var h=current_project["Programming/Scripting Languages"][f];0==b.filter(function(a){return a.id==h}).length&&b.push({group:"2",id:h});d.push({source:c,target:h,value:"1"})}for(var e in current_project["Tools/Frameworks"]){var k=current_project["Tools/Frameworks"][e];0==b.filter(function(a){return a.id==k}).length&&b.push({group:"3",
id:k});d.push({source:c,target:k,value:"1"})}for(var n in current_project.OS){var l=current_project.OS[n];0==b.filter(function(a){return a.id==l}).length&&b.push({group:"4",id:l});d.push({source:c,target:l,value:"1"})}for(var p in current_project["Other Skills"]){var m=current_project["Other Skills"][p];0==b.filter(function(a){return a.id==m}).length&&b.push({group:"5",id:m});d.push({source:c,target:m,value:"1"})}}return NodeLink_data={nodes:b,links:d}}
function get_item_by_key_value(a,b,d){for(var c in a)if(c[b]=d)return c}function find_values_by_key(a,b,d){d=void 0===d?!1:d;output=[];for(var c in a)!1===d?c==b?output=output.concat([a[c]]):"object"==typeof a[c]&&(output=output.concat(find_values_by_key(a[c],b,d=!1))):!0===d&&(c.includes(b)?output=output.concat([a[c]]):"object"==typeof a[c]&&(output=output.concat(find_values_by_key(a[c],b,d=!0))));return output}
var all_projects=Object.keys(skillset),all_programming=[].concat($jscomp.arrayFromIterable(new Set(find_values_by_key(skillset,"Programming/Scripting Languages").flat()))),all_tools=[].concat($jscomp.arrayFromIterable(new Set(find_values_by_key(skillset,"Tools/Frameworks").flat()))),all_OSs=[].concat($jscomp.arrayFromIterable(new Set(find_values_by_key(skillset,"OS").flat()))),all_others=[].concat($jscomp.arrayFromIterable(new Set(find_values_by_key(skillset,"Other Skills").flat()))),total_length=
all_projects.length+all_programming.length+all_tools.length+all_OSs.length+all_others.length,all_names=[];all_names.push(all_projects);all_names.push(all_programming);all_names.push(all_tools);all_names.push(all_OSs);all_names.push(all_others);all_names=all_names.flat();var tmp_hidden_connection_value=30;
function skills_to_dependency_matrix(a){var b=[],d=0,c;for(c in a){var f=[];f.push(0);all_projects.forEach(function(a){f.push(0)});all_programming.forEach(function(b){a[c]["Programming/Scripting Languages"].includes(b)?f.push(2):f.push(0)});all_tools.forEach(function(b){a[c]["Tools/Frameworks"].includes(b)?f.push(2):f.push(0)});all_OSs.forEach(function(b){a[c]["Tools/Frameworks"].includes(b)?f.push(2):f.push(0)});all_others.forEach(function(b){a[c]["Other Skills"].includes(b)?f.push(2):f.push(0)});
f.push(0);b.push(f);d++}var h=[];h.push(0);for(d=0;d<total_length;d++)h.push(0);h.push(tmp_hidden_connection_value);b.push(h);all_programming.forEach(function(c){var d=[];all_projects.forEach(function(b){a[b]["Programming/Scripting Languages"].includes(c)?d.push(1):d.push(0)});d.push(0);for(var e=0;e<all_programming.length+all_tools.length+all_OSs.length+all_others.length;e++)d.push(0);d.push(0);b.push(d)});all_tools.forEach(function(d){var c=[];all_projects.forEach(function(b){a[b]["Tools/Frameworks"].includes(d)?
c.push(1):c.push(0)});c.push(0);for(var e=0;e<all_programming.length+all_tools.length+all_OSs.length+all_others.length;e++)c.push(0);c.push(0);b.push(c)});all_OSs.forEach(function(c){var d=[];all_projects.forEach(function(b){a[b].OS.includes(c)?d.push(1):d.push(0)});d.push(0);for(var e=0;e<all_programming.length+all_tools.length+all_OSs.length+all_others.length;e++)d.push(0);d.push(0);b.push(d)});all_others.forEach(function(d){var c=[];all_projects.forEach(function(b){a[b]["Other Skills"].includes(d)?
c.push(1):c.push(0)});c.push(0);for(var e=0;e<all_programming.length+all_tools.length+all_OSs.length+all_others.length;e++)c.push(0);c.push(0);b.push(c)});h=[];h.push(0);for(d=0;d<total_length;d++)h.push(0);h.push(0);h[all_projects.length]=tmp_hidden_connection_value;b.push(h);return b}function respondent_calculator(a){for(var b=0,d=0;d<a.length;d++)for(var c=d;c<a.length;c++)b+=a[d][c];return b-tmp_hidden_connection_value}
var matrix=skills_to_dependency_matrix(skillset),respondents=respondent_calculator(matrix),emptyPerc=.2,emptyStroke=Math.round(respondents*emptyPerc);tmp_hidden_connection_value=emptyStroke;matrix=skills_to_dependency_matrix(skillset);
var offset=emptyStroke/(respondents+emptyStroke)*Math.PI/2,screenWidth=$(window).width(),screenHeight=$(window).height(),margin={left:0,top:0,right:0,bottom:0},width=Math.min(screenWidth,800)-margin.left-margin.right,height=Math.min(screenWidth,800)-margin.top-margin.bottom,chord=d3.layout.chord().padding(.05).sortSubgroups(d3.descending).matrix(matrix),innerRadius=600<screenWidth?.17*Math.min(width,height):.25*Math.min(width,height);outerRadius=1.2*innerRadius;
var fill=d3.scale.ordinal().domain(d3.range(4)).range(["#000000","#FFDD89","#957244","#F26223"]),svg=d3.select("#skill_svg").attr("viewBox","0 0 "+width+" "+height).append("g").attr("transform","translate("+width/2+","+height/2+")");
svg.append("g").selectAll("path").data(chord.groups).enter().append("path").style("fill",function(a){if(a.index<all_projects.length+1)return"#53e8ea";if(a.index>=all_projects.length+1&&a.index<all_projects.length+all_programming.length+1)return"#FFDD89";if(a.index>=all_projects.length+1+all_programming.length&&a.index<all_projects.length+all_programming.length+all_tools.length+1)return"#F26223";if(a.index>=all_projects.length+1+all_programming.length+all_tools.length&&a.index<all_projects.length+
all_programming.length+all_tools.length+all_OSs.length+1)return"#957244";if(a.index>=all_projects.length+all_programming.length+all_tools.length+all_OSs.length&&a.index+1)return"#000000"}).style("stroke",function(a){if(a.index<all_projects.length+1)return"#53e8ea";if(a.index>=all_projects.length+1&&a.index<all_projects.length+all_programming.length+1)return"#FFDD89";if(a.index>=all_projects.length+1+all_programming.length&&a.index<all_projects.length+all_programming.length+all_tools.length+1)return"#F26223";
if(a.index>=all_projects.length+1+all_programming.length+all_tools.length&&a.index<all_projects.length+all_programming.length+all_tools.length+all_OSs.length+1)return"#957244";if(a.index>=all_projects.length+1+all_programming.length+all_tools.length+all_OSs.length&&a.index)return"#000000"}).style("opacity",function(a){return a.index==total_length+1||a.index==all_projects.length?0:1}).attr("d",d3.svg.arc().innerRadius(innerRadius).outerRadius(outerRadius).startAngle(startAngle).endAngle(endAngle)).on("mouseover",
fade(.1,"mouseover")).on("mouseout",fade(.8,"mouseout")).on("dblclick",function(a){d3.select("#tooltip").transition().style("opacity",0);a='<p align="justify" style="white-space: normal;">'+skillset[all_projects[a.index]].description+"</p>";d3.select("#projectdescription").html(a).style("top",function(){return d3.event.pageY-30+"px"}).style("right",function(){return screenWidth-d3.event.pageX+"px"});d3.select("#projectdescription").transition().style("opacity",.9).style("z-index",10)});
svg.append("g").attr("class","chord").selectAll("path").data(chord.chords).enter().append("path").attr("d",d3.svg.chord().radius(innerRadius).startAngle(startAngle).endAngle(endAngle)).style("fill",function(a){if(a.target.index<all_projects.length+1)return"#957244";if(a.target.index>=all_projects.length+1&&a.target.index<all_projects.length+all_programming.length+1)return"#FFDD89";if(a.target.index>=all_projects.length+1+all_programming.length&&a.target.index<all_projects.length+all_programming.length+
all_tools.length+1)return"#F26223";if(a.target.index>=all_projects.length+1+all_programming.length+all_tools.length&&a.target.index<all_projects.length+all_programming.length+all_tools.length+all_OSs.length+1)return"#957244";if(a.target.index>=all_projects.length+1+all_programming.length+all_tools.length+all_OSs.length&&a.index)return"#000000"}).style("opacity",function(a){return a.target.index==total_length+1||a.target.index==all_projects.length?0:.8}).on("mouseover",function(){d3.select(this).style("opacity",
function(a){return a.target.index==total_length+1||a.target.index==all_projects.length?0:.3})}).on("mouseout",function(){d3.select(this).style("opacity",function(a){return a.target.index==total_length+1||a.target.index==all_projects.length?0:1})});function groupTicks(a){var b=(a.endAngle-a.startAngle)/a.value;return d3.range(0,a.value,1E3).map(function(d,c){return{angle:d*b+a.startAngle,label:c%5?null:d/1E3+"k"}})}
var wrapper=svg.append("g").attr("class","chordWrapper"),g=wrapper.selectAll("g.group").data(chord.groups).enter().append("g").attr("class","group");
g.append("text").each(function(a){a.angle=(a.startAngle+a.endAngle)/2+offset}).attr("dy",".35em").attr("class","titles").attr("text-anchor",function(a){return a.angle>Math.PI?"end":null}).attr("transform",function(a,b){return"rotate("+(180*a.angle/Math.PI-90)+")translate("+(outerRadius+7)+")"+(a.angle>Math.PI?"rotate(180)":"")}).text(function(a,b){if(b>all_projects.length)return all_names[b-1];if(b!=all_projects.length&&b!=total_length+1)return all_names[b]});
function fade(a,b){return function(d,c){c!=total_length+1&&c!=all_projects.length&&(c<all_projects.length&&("mouseover"==b?(d3.select("#tooltip").html("Double click/tap for more information").style("top",function(){return d3.event.pageY-30+"px"}).style("left",function(){return d3.event.pageX-30+"px"}),d3.select("#tooltip").transition().style("opacity",.9)):d3.select("#tooltip").transition().style("opacity",0)),svg.selectAll(".chord path").filter(function(a){return a.source.index!=c&&a.target.index!=
c&&a.source.index!=all_projects.length&&a.source.index!=total_length+1}).transition().style("opacity",a))}}function startAngle(a){return a.startAngle+offset}function endAngle(a){return a.endAngle+offset}$("div:not(#projectdescription)").click(function(){d3.select("#projectdescription").transition().style("opacity",0).style("z-index",-1)});
function matrix_to_category_matrix(a){for(var b=[],d=0,c=0,f=0,h=0,e=0;e<total_length;e++)if(e>all_projects.length&&e!=total_length+1)for(var k=0;k<all_projects.length;k++)e>=all_projects.length+1&&e<all_projects.length+all_programming.length+1?d+=2*a[e][k]:e>=all_projects.length+all_programming.length+1&&e<all_projects.length+all_programming.length+all_tools.length+1?c+=2*a[e][k]:e>=all_projects.length+all_programming.length+all_tools.length+1&&e<all_projects.length+all_programming.length+all_tools.length+
all_OSs.length+1?f+=2*a[e][k]:e>=all_projects.length+all_programming.length+all_tools.length+all_OSs.length+1&&e<all_projects.length+all_programming.length+all_tools.length+all_OSs.length+all_others.length+1&&(h+=2*a[e][k]);b.push([0,d,c,f,h,0,0]);b.push([0,0,0,0,0,0,tmp_hidden_connection_value]);b.push([d,0,0,0,0,0,0]);b.push([c,0,0,0,0,0,0]);b.push([f,0,0,0,0,0,0]);b.push([h,0,0,0,0,0,0]);b.push([0,tmp_hidden_connection_value,0,0,0,0,0]);return b}
if(600<screenWidth){var cat_matrix=matrix_to_category_matrix(matrix);respondents=respondent_calculator(cat_matrix);emptyPerc=.2;tmp_hidden_connection_value=emptyStroke=Math.round(respondents*emptyPerc);cat_matrix=matrix_to_category_matrix(matrix);var chord2=d3.layout.chord().padding(.01).sortSubgroups(d3.descending).matrix(cat_matrix);svg.append("g").selectAll("path").data(chord2.groups).enter().append("path").style("fill",function(a){return 0==a.index?"#53e8ea":2==a.index?"#FFDD89":3==a.index?"#F26223":
4==a.index?"#957244":"#000000"}).style("stroke",function(a){return 0==a.index?"#53e8ea":2==a.index?"#FFDD89":3==a.index?"#F26223":4==a.index?"#957244":"#000000"}).style("opacity",function(a){return 1==a.index||6==a.index?0:1}).attr("d",d3.svg.arc().innerRadius(2*innerRadius).outerRadius(2*innerRadius+2).startAngle(startAngle).endAngle(endAngle));wrapper=svg.append("g").attr("class","chordWrapper");g=wrapper.selectAll("g.group").data(chord2.groups).enter().append("g").attr("class","group");group_names=
"Projects  Programming Tools OSs Others ".split(" ");g.append("text").each(function(a){a.angle=(a.startAngle+a.endAngle)/2+offset}).attr("dy",".35em").attr("class","titles").attr("text-anchor",function(a){return"middle"}).attr("transform",function(a,b){return"rotate("+(180*a.angle/Math.PI-90)+")translate("+(2*innerRadius+20)+")rotate(90)"}).text(function(a,b){return group_names[b]})};